config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
        registrations: 'users/registrations'
        }
  resources :volunteers do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
  get 'search', to: 'volunteers#search'
  resource :order_managements, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :good_evaluations, only: [:create, :destroy]
  resources :categories


  root 'top#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" # if Rails.env.development?
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  belongs_to :user
  has_many :order_managements, dependent: :destroy
  has_many :contractors, through: :order_managements, source: :user, dependent: :destroy
  has_many :categorizings, dependent: :destroy
  has_many :categories, through: :categorizings
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :title, presence: true, length: {maximum: 30}
  validates :describe, presence: true, length: {maximum: 300}
  validates :address, presence: true, length: {maximum: 300}
  validates :date, presence: true
  validates :capacity, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}

  validate :date_is_not_past


  def date_is_not_past
    errors.add(:date, "は過去の日時です") if date < DateTime.now
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_volunteer, only: [:edit, :update, :show, :destroy]
  before_action :search_params, only: [:search]

  PER = 10

  def index
    @q = Volunteer.ransack(params[:q])
    @categories = Category.all
    @volunteers = @q.result.includes(:user).page(params[:page]).order(created_at: :desc).per(PER)
  end

  def search
    @q = Volunteer.search(search_params)
    @volunteers = @q.result.includes(:user)
  end

  def new
    @volunteer = Volunteer.new
  end

  def create
    @volunteer = Volunteer.new(volunteer_params)
    @volunteer[:image] = "/assets/default.png" if params[:image].nil?
    @volunteer.user_id = current_user.id
    if @volunteer.save
      VolunteerMailer.volunteer_mail(@volunteer).deliver
      redirect_to volunteers_path, notice: 'ボランティア依頼を作成しました！'
    else
      render :new
    end
  end

  def edit
    if @volunteer.user_id != current_user.id
      redirect_to volunteers_path, alert: 'not your task!'
    end
  end

  def update
    if @volunteer.user_id == current_user.id
      if @volunteer.update(volunteer_params)
        redirect_to volunteer_path(@volunteer), notice: 'ボランティア内容を編集しました。'
      else
        render :edit
      end
    else
      redirect_to volunteers_path, alert: '実行できません'
    end
  end

  def show
    @order_management = current_user.order_managements.find_by(volunteer_id: @volunteer.id) if user_signed_in?
    @comments = @volunteer.comments.includes(:user).order(created_at: :desc)
    @comment = @volunteer.comments.build
  end

  def destroy
    if @volunteer.user_id == current_user.id
      VolunteerMailer.delete_mail(@volunteer).deliver
      @volunteer.destroy
      redirect_to volunteers_path, notice: 'ボランティアを削除しました。'
    else
      redirect_to volunteers_path, alert: '実行できません'
    end
  end

  private

  def set_volunteer
    @volunteer = Volunteer.find(params[:id])
  end

  def volunteer_params
    params.require(:volunteer).permit(:title, :describe, :image, :image_cache, :remove_image, :address, :capacity, :date, category_ids: [])
  end

  def search_params
    params.require(:q).permit(:title_cont, :categories_id_eq)
  end

end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_form.html.erb
<div class="row">
  <%= form_with(model: volunteer, local: true) do |form| %>
    <% if volunteer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(volunteer.errors.count, "エラー") %> ボランティアが保存できませんでした:</h2>
        <ul>
        <% volunteer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field col-sm-12 col-md-10 col-lg-8">
      <%= form.label :依頼するボランティアのタイトル %>
      <%= form.text_field :title, class: 'form-control', placeholder: 'タイトルを入力' %>
    </div>

    <div class="field col-sm-12 col-md-10 col-lg-8">
      <%= form.label :ボランティアの詳細 %>
      <%= form.text_area :describe, class: 'form-control', placeholder: '詳細を入力' %>
    </div>
    <br>

    <div class="field col-sm-12 col-md-10 col-lg-8">
      <%= form.file_field :image, id: :volunteer_img %>
      <% if @volunteer.image.present? %>
        <%= image_tag @volunteer.image.url, id: :img_prev  %>
      <% else %>
        <%= image_tag "default.png", id: :img_prev %>
      <% end %>
      <script type="text/javascript">
        $(function() {
          function readURL(input) {
            if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
          $('#img_prev').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
            }
          }
          $("#volunteer_img").change(function(){
            readURL(this);
          });
        });
      </script>
    </div>

    <div class="field col-sm-12 col-md-10 col-lg-8">
      <%= form.label :住所 %>
      <%= form.text_field :address, class: 'form-control', placeholder: '住所を入力' %>
    </div>

    <div class="field col-sm-12 col-md-10 col-lg-8">
      <%= form.label :定員 %>
      <%= form.number_field :capacity, class: 'form-control' %>
    </div>

    <div class="field col-sm-12 col-md-10 col-lg-8">
      <%= form.label :日時 %>
      <%= form.datetime_field :date, class: 'form-control' %>
    </div>

    <div class="col-12 clearfix">
      <div class="float-left">
        <% Category.all.each do |category| %>
             <table class="float-left">
               <thead>
                 <tr>
                   <th>
                     <%= form.check_box :category_ids, { multiple: true, checked: category[:checked],
                        disabled: category[:disabled], include_hidden: false }, category[:id] %>
                        <%= category.name %>
                    </th>
                 </tr>
               </thead>
               <tbody>
                 <tr>
                   <td>
                     <% if category.icon.present? %>
                      <%= image_tag category.icon_url, class: 'rounded-circle' %>
                     <% end %>
                  </td>
                 </tr>
               </tbody>
             </table>
        <% end %>
      </div>
    </div>
      <%= form.submit  class: 'btn btn-primary' %>
      <%= link_to '戻る', volunteers_path, class: 'btn btn-primary' %>
<% end %>
</div>

app/views/volunteers/_search_form.html.erb
<div class="col-12 clearfix">
  <form class="form-inline float-right">
    <%= search_form_for(@q, url:volunteers_path) do |f| %>
      <div class="form-group mb-6">
        <%= f.label :title_cont, 'タイトル' %>
        <%= f.search_field :title_cont, class: 'form-control' %>
      </div>

      <div class="form-group mx-sm-3 mb-6">
        <%= f.label :categories_id_eq, 'カテゴリー' %>
        <%= f.collection_select :categories_id_eq, @categories, :id, :name, include_blank: '指定なし' %>
      </div>

      <%= image_submit_tag "red_search.png", id: 'search_btn' %>

    <% end %>
  </form>
</div>

app/views/volunteers/edit.html.erb
<div class="volunteers_body">
  <h1>ボランティアを修正</h1>
  <div class="form-group">
    <%= render 'form', volunteer: @volunteer %>
  </div>
</div>
<footer>
  <%= link_to '詳細を確認', @volunteer, class: 'btn btn-primary' %>
</footer>

app/views/volunteers/index.html.erb
<div class="row">
  <div class="col-12 text-center font-weight-bolder">
    <h2>ボランティア依頼一覧</h2>
    <br>
  </div>
  <div class="col-12">
    <%= render 'search_form' %>
  </div>
</div>
<!-- <%= image_tag "vol_top.png", class: 'icon image-fluid' %> -->
<br>
<br>
<table>
  <tr>
    <th>依頼者</th>
    <th>依頼名</th>
    <th>詳細</th>
    <th>ステータス</th>
  </tr>
  <% @volunteers.each do |volunteer| %>
    <tr>
      <td class="icon">
        <a href="/users/<%= volunteer.user.id %>"><%= volunteer.user.name %></a>
        <br>
        <a href="/users/<%= volunteer.user.id %>"><%= image_tag volunteer.user.icon.url, class: "top_icon rounded-circle" %></a>
      </td>
      <td><a href="/volunteers/<%= volunteer.id %>"><%= volunteer.title.truncate(10) %></a></td>
      <td class="describe"><%= volunteer.describe.truncate(20) %></td>
      <td><%= "#{volunteer.contractors.count}人/#{volunteer.capacity}人" %></td>
    </tr>
  <% end %>
</table>
<%= paginate @volunteers %>
<br>
<%= link_to 'ボランティア新規登録', new_volunteer_path, class: 'btn2 mx-auto d-block' %>

<style>
  table{
  border-collapse: collapse;
  border-spacing: 0;
  width: 100%;
  }

  table tr{
    border-bottom: solid 1px #eee;
    cursor: pointer;
  }

  table tr:hover{
    background-color: #d4f0fd;
  }

  table th,table td{
    text-align: center;
    width: 25%;
    padding: 15px 0;
  }

  .describe {
    text-align: left;
  }

  table td.icon{
    background-size: 35px;
    background-position: left 5px center;
    background-repeat: no-repeat;
    padding-left: 30px;
  }

</style>

app/views/volunteers/new.html.erb
<div class="volunteers_body">
  <h2>新しい依頼を作成</h2>
  <%= render 'form', volunteer: @volunteer %>
</div>

app/views/volunteers/show.html.erb
<div class="row">

  <div class="col-5">
    <h3><%= @volunteer.title %></h3>
    <table class="table">
      <tr>
        <td>依頼者</td>
        <td><a href="/users/<%= @volunteer.user.id %>"><%= "#{@volunteer.user.name.truncate(10)}" %></a></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><%= @volunteer.address %> <a href="https://www.google.co.jp/maps" target="_blank">Map</a></td>
      </tr>
      <tr>
        <td>ステータス</td>
        <td><%= "受注者#{@volunteer.contractors.count}人/定員#{@volunteer.capacity}人" %></td>
      </tr>
      <tr>
        <td>日付</td>
        <td><%= l @volunteer.date %></td>
      </tr>
      <tr>
        <td>受注した人数</td>
        <td><%= @volunteer.contractors.count %>人</td>
      </tr>
      <tr>
        <td>受注した人</td>
        <td>
          <ul>
            <% @volunteer.contractors.each do |vc| %>
              <li><a href="/users/<%= vc.id %>"><%= "#{vc.name.truncate(10)}" %></a></li>
            <% end %>
          </ul>
        </td>
      </tr>
    </table>
    <p><strong>カテゴリー</strong></p>
    <div class="col-12 clearfix">
      <div class="float-left">
        <div class="row">
          <% @volunteer.categories.each do |vc| %>
          <div class="col-4 text-center">
            <%= vc.name %>
            <%= image_tag vc.icon.url, class: 'rounded-circle', size: '100x100' %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-7">
    <p>
      <% if @volunteer.image? && @volunteer.image.url %>
        <%= image_tag @volunteer.image.url, class: 'mx-auto d-block show_icon' %>
      <% else %>
        <image src="/assets/default.png" class="mx-auto d-block show_icon" >
      <% end %>
    </p>
    <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="card">
        <div class="card-header" role="tab" id="headingOne">
          <h5 class="mb-0">
            <a class="text-body d-block p-3 m-n3 text-center" data-toggle="collapse" href="#collapseOne" role="button" aria-expanded="true" aria-controls="collapseOne">
              ボランティア詳細
            </a>
          </h5>
        </div><!-- /.card-header -->
        <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
          <div class="card-body">
            <%= @volunteer.describe %>
          </div><!-- /.card-body -->
        </div><!-- /.collapse -->
      </div><!-- /.card -->
    </div><!-- /#accordion -->
    <br>
    <!-- 受注機能 -->
    <%= render 'order_managements/order' %>
  </div>
</div>


  <!-- コメント機能 -->
  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, volunteer: @volunteer } %>
  </div>
  <%= render partial: 'comments/form', locals: { comment: @comment, volunteer: @volunteer } %>
  <br>
  <% if user_signed_in? %>
    <% if @volunteer.user.id == current_user.id  %>
      <%= link_to '編集', edit_volunteer_path(@volunteer), class: 'btn btn-primary' %>
      <%= link_to '依頼を削除', @volunteer, method: :delete, data: { confirm: '依頼を削除しますか？' }, class: 'btn btn-danger' %>
    <% end %>
  <% end %>
  <%= link_to '戻る', volunteers_path, class: 'btn btn-primary' %>