config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
        registrations: 'users/registrations'
        }
  resources :volunteers do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
  get 'search', to: 'volunteers#search'
  resource :order_managements, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :good_evaluations, only: [:create, :destroy]
  resources :categories


  root 'top#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" # if Rails.env.development?
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :volunteer, optional: true

  validates :content, length: {maximum: 200}, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_volunteer, only: [:create, :edit, :update, :destroy]

  def create
    @comment = @volunteer.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        # format.html { redirect_to volunteer_path(@volunteer), notice: '投稿できませんでした' }
        format.js { render :index }
      end
    end
  end

  def edit
    @comment = @volunteer.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @comment = @volunteer.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        flash.now[:notice] = 'コメントが編集されました'
        format.js { render :index }
      else
        # flash.now[:notice] = 'コメントの編集に失敗しました'
        # format.js { redirect_to volunteer_path(@volunteer), notice: '編集できませんでした' }
        format.js { render :index }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.destroy
        format.js { render :index }
      else
        format.html { redirect_to volunteer_path(@volunteer), notice: '削除できませんでした' }
      end
    end
  end


  private

  def set_comment
    @comment = Comment.find_by(id: params[:id], volunteer_id: params[:volunteer_id])
  end


  def set_volunteer
    @volunteer = Volunteer.find(params[:volunteer_id])
  end

  def comment_params
    params.require(:comment).permit(:volunteer_id, :content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<div id="comment_edit_form">
  <%= form_with(model: [volunteer, comment]) do |form| %>
    <div class="input-field">
      <%= form.text_area :content, class: 'form-control', id: "comment_content_#{volunteer.id}" %>
      <%= form.submit '編集' %>
    </div>
  <% end %>
</div>

app/views/comments/_edit_error.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <%= render 'layouts/flashes' %>
    <h5><%= @comment.errors.count %>件のエラーがあります。</h5>
    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/comments/_error.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <%= render 'layouts/flashes' %>
    <h5><%= @comment.errors.count %>件のエラーがあります。</h5>
    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <%= form_with(model: [volunteer, comment])  do |form| %>
    <div class="field">
      <%= form.text_area :content, class: 'form-control', placeholder: 'コメントを入力'  %>
    </div>
    <br>
    <div class="actions">
      <%= form.submit 'コメントする', class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

app/views/comments/_form_index.html.erb
<h3 class="mt-5">コメント一覧</h3>
<% @comments.each do |comment| %>
  <div>
    <% unless comment.user.icon.blank? %>
      <a href="/users/<%= comment.user.id %>">
        <%= image_tag comment.user.icon.to_s, class:"rounded-circle icon_image mr-3 mb-3"%>
      </a>
    <% else %>
      <a href="/users/<%= comment.user.id %>">
        <%= "#{comment.user.name}:" %>
      </a>
    <% end %>
    <%= comment.content %>
    <% if user_signed_in? %>
      <% if current_user.id == comment.user.id %>
        <p>
          <%=link_to "削除", volunteer_comment_path(comment.volunteer.id, comment.id), method: :delete, data: {confirm: 'コメントを削除しますか？'} %>
        </p>
      <% end %>
    <% end %>
    <hr>
  </div>
<% end %>

<% if user_signed_in? %>
  <%= form_for [@volunteer, @comment] do |form| %>
    <div class="form-group">
      <%= form.text_field :content  %>
    </div>
    <%= form.submit 'コメントする' %>
  <% end %>
<% end %>

app/views/comments/_index.html.erb
</br>
<strong>コメント一覧</strong>
<%= render partial: 'comments/error' %>
</br>
<% comments.order(created_at: :desc).each do |comment| %>
  <div class="row">
    <div class="col-2">
      <a href="/users/<%= comment.user.id %>"><%= "#{comment.user.name.truncate(10)}" %></a>
      <% unless comment.user.icon.blank? %>
        <a href="/users/<%= comment.user.id %>">
          <%= image_tag comment.user.icon.to_s, class:"rounded-circle", size: '100x100'%>
        </a>
      <% end %>
    </div>

    <div class="col-10">
      <div id="errors_area_<%= comment.id %>">
      </div>
      <div class="comment-content" id ="this_comment_<%= comment.id %>">
        <%= comment.content %>
      </div>
      <p><font size="-2"><%= time_ago_in_words(comment.created_at) %>前</font></p>
      <% if user_signed_in? %>
        <% if current_user.id == comment.user.id %>
          <span class="badge">
            <%=link_to "削除", volunteer_comment_path(comment.volunteer.id, comment.id), method: :delete, remote: true,
             data: {confirm: 'コメントを削除しますか？'} %>
          </span>
          <span class="badge"><%= link_to "編集", edit_volunteer_comment_path(volunteer, comment), remote: true %></span>
        <% end %>
      <% end %>
    </div>

    <hr>
  </div>
<% end %>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', volunteer: @volunteer, comment: @comment %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.volunteer.comments, volunteer: @comment.volunteer }) %>")
$("textarea").val('')

app/views/comments/update.js.erb
$('#comments_area').replaceWith
("<%=j render 'comments/index',volunteer: @volunteer, comment: @comment, comments: @volunteer.comments, remote: true %>");