config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
        registrations: 'users/registrations'
        }
  resources :volunteers do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
  get 'search', to: 'volunteers#search'
  resource :order_managements, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :good_evaluations, only: [:create, :destroy]
  resources :categories


  root 'top#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" # if Rails.env.development?
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorizing.rb
class Categorizing < ApplicationRecord
  belongs_to :volunteer
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizings, dependent: :destroy
  has_many :volunteers, through: :categorizings
  mount_uploader :icon, ImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :volunteer, optional: true

  validates :content, length: {maximum: 200}, presence: true
end

app/models/good_evaluation.rb
class GoodEvaluation < ApplicationRecord
  belongs_to :user
  belongs_to :evaluate_user, class_name: 'User'
end

app/models/order_management.rb
class OrderManagement < ApplicationRecord
  belongs_to :user
  belongs_to :volunteer

  def ordered_by?(user) #current_userがそのvolunteerを受注していればtrueというメソッド。volunteerのビューで使おう。
    order_managements.where(user_id: user.id).exists?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :volunteers, dependent: :destroy
  has_many :order_managements, dependent: :destroy
  has_many :ordered_volunteers, through: :order_managements, source: :volunteer, dependent: :destroy
  has_many :comments
  has_many :good_evaluations
  has_many :evaluatings, through: :good_evaluations, source: :evaluate_user
  has_many :reverse_good_evaluations, class_name: 'GoodEvaluation', foreign_key: 'evaluate_user_id'
  has_many :evaluated_users, through: :reverse_good_evaluations, source: :user
  mount_uploader :icon, ImageUploader
  validates :name, presence: true

  def evaluate(other_user)
    unless self == other_user
      self.good_evaluations.find_or_create_by(evaluate_user_id: other_user.id)
    end
  end

  def unevaluate(other_user)
    good_evaluation = self.good_evaluations.find_by(evaluate_user_id: other_user.id)
    good_evaluation.destroy if good_evaluation
  end

  def evaluating?(other_user)
    self.evaluatings.include?(other_user)
  end


end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  belongs_to :user
  has_many :order_managements, dependent: :destroy
  has_many :contractors, through: :order_managements, source: :user, dependent: :destroy
  has_many :categorizings, dependent: :destroy
  has_many :categories, through: :categorizings
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :title, presence: true, length: {maximum: 30}
  validates :describe, presence: true, length: {maximum: 300}
  validates :address, presence: true, length: {maximum: 300}
  validates :date, presence: true
  validates :capacity, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}

  validate :date_is_not_past


  def date_is_not_past
    errors.add(:date, "は過去の日時です") if date < DateTime.now
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_volunteer, only: [:create, :edit, :update, :destroy]

  def create
    @comment = @volunteer.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        # format.html { redirect_to volunteer_path(@volunteer), notice: '投稿できませんでした' }
        format.js { render :index }
      end
    end
  end

  def edit
    @comment = @volunteer.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @comment = @volunteer.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        flash.now[:notice] = 'コメントが編集されました'
        format.js { render :index }
      else
        # flash.now[:notice] = 'コメントの編集に失敗しました'
        # format.js { redirect_to volunteer_path(@volunteer), notice: '編集できませんでした' }
        format.js { render :index }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.destroy
        format.js { render :index }
      else
        format.html { redirect_to volunteer_path(@volunteer), notice: '削除できませんでした' }
      end
    end
  end


  private

  def set_comment
    @comment = Comment.find_by(id: params[:id], volunteer_id: params[:volunteer_id])
  end


  def set_volunteer
    @volunteer = Volunteer.find(params[:volunteer_id])
  end

  def comment_params
    params.require(:comment).permit(:volunteer_id, :content)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "warning"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/good_evaluations_helper.rb
module GoodEvaluationsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %>">
    <strong>
      <%= value %>
    </strong>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VolunteerUp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="" >
        <a class="" href="/"><%= image_tag "volunteer_nav.png", class: 'rounded-circle', size: '100x100' %></a>
        <%= link_to "VolunteerUp", volunteers_path, id: "head-log", class: "header-log" %>
        <ul class="nav-list">
          <% if user_signed_in? %>
            <li class="nav-list-item"><%= link_to "ボランティア一覧", volunteers_path, class: "nav-list-item" %></li>
            <li class="nav-list-item">
              <%= link_to "#{current_user.name}のプロフィール", user_path(current_user.id), class: "nav-list-item" %>
            </li>
            <li class="nav-list-item"><%= link_to "ログアウトする", destroy_user_session_path, method: :delete , class: "nav-list-item"%></li>
          <% else %>
            <li class="nav-list-item"><%= link_to "ボランティア一覧", volunteers_path, class: "nav-list-item" %></li>
            <li class="nav-list-item"><%= link_to "新規ユーザー登録", new_user_registration_path, class: "nav-list-item" %></li>
            <li class="nav-list-item"><%= link_to "ログインする", new_user_session_path, class: "nav-list-item" %></li>
          <% end %>
        </ul>
      </nav>
      <!-- <image src="/assets/inaka.jpg" > -->
    </header>
    <%= render 'layouts/flashes' %>
    <div class="container">
      <br>
      <%= yield %>
    </div>
    <footer>
      <nav class="" >
        <ul class="nav-list">
          <% if user_signed_in? %>
            <li class="nav-list-item"><%= link_to "ボランティア一覧", volunteers_path, class: "nav-list-item" %></li>
            <li class="nav-list-item">
              <%= link_to "#{current_user.name}のプロフィール", user_path(current_user.id), class: "nav-list-item" %>
            </li>
            <li class="nav-list-item"><%= link_to "ログアウトする", destroy_user_session_path, method: :delete , class: "nav-list-item"%></li>
          <% else %>
            <li class="nav-list-item"><%= link_to "ボランティア一覧", volunteers_path, class: "nav-list-item" %></li>
            <li class="nav-list-item"><%= link_to "新規ユーザー登録", new_user_registration_path, class: "nav-list-item" %></li>
            <li class="nav-list-item"><%= link_to "ログインする", new_user_session_path, class: "nav-list-item" %></li>
          <% end %>
        </ul>
    </footer>
  </body>
</html>

<style>
  header .header-log {
    font-size: 40px;
    line-height: 100px;
    color: #FFF;
  }
  .nav-list {
    text-align: center;
    line-height: 100px;
    color: #FFF;
  }
  .nav-list-item {
    list-style: none;
    display: inline-block;
    margin: 0 20px;
    color: #FFF;
  }

  footer .nav-list-item:hover {
    color:#fff;
  }
</style>